item {
  id: 1
  name: '-'
}

item {
  id: 2
  name: 'almond'
}

item {
  id: 3
  name: 'apple'
}

item {
  id: 4
  name: 'avocado'
}

item {
  id: 5
  name: 'beef'
}

item {
  id: 6
  name: 'bell pepper'
}

item {
  id: 7
  name: 'blueberry'
}

item {
  id: 8
  name: 'bread'
}

item {
  id: 9
  name: 'broccoli'
}

item {
  id: 10
  name: 'butter'
}

item {
  id: 11
  name: 'carrot'
}

item {
  id: 12
  name: 'cheese'
}

item {
  id: 13
  name: 'chilli'
}

item {
  id: 14
  name: 'cookie'
}

item {
  id: 15
  name: 'corn'
}

item {
  id: 16
  name: 'cucumber'
}

item {
  id: 17
  name: 'egg'
}

item {
  id: 18
  name: 'eggplant'
}

item {
  id: 19
  name: 'garlic'
}

item {
  id: 20
  name: 'lemon'
}

item {
  id: 21
  name: 'milk'
}

item {
  id: 22
  name: 'mozarella cheese'
}

item {
  id: 23
  name: 'mushroom'
}

item {
  id: 24
  name: 'mussel'
}

item {
  id: 25
  name: 'onion'
}

item {
  id: 26
  name: 'oyster'
}

item {
  id: 27
  name: 'parmesan cheese'
}

item {
  id: 28
  name: 'pasta'
}

item {
  id: 29
  name: 'pork rib'
}

item {
  id: 30
  name: 'potato'
}

item {
  id: 31
  name: 'salmon'
}

item {
  id: 32
  name: 'scallop'
}

item {
  id: 33
  name: 'shrimp'
}

item {
  id: 34
  name: 'strawberry'
}

item {
  id: 35
  name: 'toast bread'
}

item {
  id: 36
  name: 'tomato'
}

item {
  id: 37
  name: 'tuna'
}

item {
  id: 38
  name: 'yogurt'
}

